services:
  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - 4000:4000
    healthcheck:
      test: ["CMD-SHELL", "curl.sh || exit 0"]
      interval: 10s
      timeout: 10s
      retries: 10
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    depends_on:
      - database
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@database:27017/
  testrunner:
    build: ./testrunner
    depends_on:
      backend:
        condition: service_healthy
