services:
  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - 4000:4000
    healthcheck:
      test: ["CMD-SHELL", "curl.sh || exit 0"]
      interval: 10s
      timeout: 10s
      retries: 10
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  testrunner:
    build: ./testrunner
    depends_on:
      backend:
        condition: service_healthy
